export const GET_CATEGORIES_FETCH: string = "GET_CATEGORIES_FETCH";
export const GET_CATEGORIES_SUCCESS: string = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE: string = "GET_CATEGORIES_FAILURE";

